### ISSUE TITLE
Extract meta data from article's urls

### ISSUE THREAD

**Issue by olivierdupuis** [discursus-io/discursus_core#9]
Add a pipeline that extract articles meta data. 

Todo
- [] Create python script that extracts meta data from article urls
- [] Add pipeline after gdelt mining that will run python script and saves output as json object in s3
- [] Add table to store enhanced mentions data
- [] Add snowpipe to stage the meta data to Snowflake
- [] Trigger refresh of snowpipe from dagster pipeline
- [] Append meta data to `articles` table.

**Comment by olivierdupuis** [comment]
Reference script: https://github.com/quakerpunk/content-audit/blob/origin/content_audit.py
